#!/usr/bin/env python
# WinKexec: kexec for Windows
# Copyright (C) 2008-2009 John Stumpo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import time

def usage():
  sys.stderr.write('''usage: %s [bin_file] [h_file] [array_name]

Converts a binary file to an unsigned char array in a C header file.
''' % sys.argv[0])
  sys.exit(1)

if len(sys.argv) != 4:
  usage()

bin_file = open(sys.argv[1], 'rb').read()

h_file = open(sys.argv[2], 'w')
h_file.write('''/* This file is generated by a script.
 * DO NOT EDIT THIS FILE!
 *
 * Created by %s from %s.
 * %s
 */

#define %s_SIZE %d
static const unsigned char %s[] = {''' %
  (sys.argv[0], sys.argv[1], time.asctime(),
   sys.argv[3].upper(), len(bin_file), sys.argv[3]))

for i in range(len(bin_file)):
  if i % 8 == 0:
    h_file.write('\n  /* 0x%08x */  0x%02x,' % (i, ord(bin_file[i])))
  else:
    h_file.write(' 0x%02x,' % ord(bin_file[i]))

h_file.write('\n};\n')
h_file.close()
